config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :movies do
    resources :reviews, except: [:show, :index]
  end 
  
  root 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
    belongs_to :user
    has_many :reviews
    has_attached_file :image, styles: { medium: "400x600#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
    belongs_to :user
    belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :movies
         has_many :reviews, dependent: :destroy
  
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid 
      user.email = auth.info.email
      user.save
    end
  end
  
  
  
  def self.new_with_session(params, session)
  if session["devise.user_attributes"]
    new(session["devise.user_attributes"], without_protection: true) do |user|
    user.attributes = params
    user.valid?
  end
  else
    super
  end
  end   
    def password_required?
      super && provider.blank?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
    @number_movies = Movie.count
    @logi = User.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
    
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :movie_lenght, :director, :rating, :image)
    end
      
        
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def all
        user= User.from_omniauth(request.env["omniauth.auth"])
        if user.persisted?
            sign_in_and_redirect user, notice: "Signed in"
    else
        session["devise.user_attributes"] = user.attributes
        redirect_to new_user_registration_url
        end
    end
    alias_method :twitter, :all
    alias_method :facebook, :all
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_movie
  before_action :authenticate_user!



  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end
    
    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
                <b><%= link_to "Movie Reviews", root_path, class: "navbar-brand"  %></b>
        </div>
                
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
            <% if user_signed_in? %>
                <li><%= @number_movies %></li>
                <li><%= link_to "New Movie", new_movie_path, class: "active" %></li>
                <li><%= link_to current_user.email, edit_user_registration_path %></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li>
                <% else %>
                <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
                <li><%= link_to "Log in", new_user_session_path, class: "active" %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
<% flash.each do |name, msg| %>
<%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>


  <div class="field">
    <%= f.label :title, class: 'logintexttxt' %><br>
    <%= f.text_field :title, class: 'logintext' %>
  </div>
  <br>
  <div class="field">
    <%= f.label :description, class: 'logintexttxt' %><br>
    <%= f.text_area :description, class: 'logindesc' %>
  </div>
  <br>
  <div class="field">
    <%= f.label :movie_lenght, class: 'logintexttxt' %><br>
    <%= f.text_field :movie_lenght, class: 'logintext' %>
  </div>
  <br>
  <div class="field">
    <%= f.label :director, class: 'logintexttxt' %><br>
    <%= f.text_field :director, class: 'logintext' %>
  </div>
  <br>
  <div class="field">
    <%= f.label :rating, class: 'logintexttxt' %><br>
    <%= f.text_field :rating, class: 'logintext' %>
  </div>
  <br>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: 'loginbutton' %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<div class="error">
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </div>
<br>
<div class="login">
<h1>Editing Movie</h1>
<% if current_user.id == @movie.user_id %>
<%= render 'form' %>
<br>
<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %> |
<%= link_to 'Destroy', @movie, method: :delete, data: { confirm: 'Are you sure?' } %>
<% else %>
<%= link_to 'Back', movies_path %>
<% end %>
</div>

app/views/movies/new.html.erb
<div class="error">
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </div>
<br>
<div class="login">
    <h1>New Movie</h1>

    <%= render 'form' %>
    <br>
    <%= link_to 'Back', movies_path %>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @movie.image.url(:medium) %>
        <div class="star-rating" data-score= <%= @avg_review %> ></div>
        <em><%= "#{@reviews.length} reviews" %></em>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @movie.title %></td>
              </tr>
              <tr>
                <td><strong>Description:</strong></td>
                <td><%= @movie.description %></td>
              </tr>
              <tr>
                <td><strong>Movie lenght:</strong></td>
                <td><%= @movie.movie_lenght %></td>
              </tr>
              <tr>
                <td><strong>Director:</strong></td>
                <td>  <%= @movie.director %></td>
              </tr>
              <tr>
                <td><strong>Rating:</strong></td>
                <td><%= @movie.rating %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Write a review", new_movie_review_path(@movie) %>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review_title"><%= @movie.title %></h1>
        <p><%= @movie.description %></p>
        
        
        <% if @reviews.blank? %>
        <h3>No reviews just yet, you can write the first one</h3>
        <%= link_to "Write a review", new_movie_review_path(@movie), class: "btn btn-danger" %>
        <% else %>
        <% @reviews.each do |review| %>
        <div class="reviews">
          <div class="star-rating" data-score=<%= review.rating %> ></div>
          <p><%= review.comment %></p>
        </div>
        <% end %>
        <% end %>
        
        
      </div>
    </div>
  </div>
        <div class="padding">
          <% if current_user.id == @movie.user_id %>
          <%= link_to 'Edit', edit_movie_path(@movie) %> |
          <% end %>
          <%= link_to 'Back', movies_path %>
        </div>
</div>

<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
      
    }
  });
</script>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment, class: 'logintexttxt' %><br>
    <%= f.text_area :comment, class: 'logindesc' %>
  </div>
  <p></p>
  <div class="actions">
    <%= f.submit class: 'loginbutton' %>
  </div>
  <br>
<% end %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<div class="editingreview">
    <h1>Editing Review</h1>

    <%= render 'form' %>

    <%= link_to 'Back', movie_path(@movie) %>
</div>

app/views/reviews/new.html.erb
<div class="login">
    <h1>New Review</h1>

    <%= render 'form' %>

    <%= link_to 'Back', movie_path(@movie) %>
</div>